import { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot, query, where } from 'firebase/firestore';
import { Activity, AlertTriangle, CalendarDays, Search, ShieldCheck, UserRound } from 'lucide-react';
import { db } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';
import { AuditLog } from '../../types/models';

type Category='all'|'finance'|'inventory'|'orders'|'access'|'settings'|'support'|'other';
const categoryInfo=(action:string,entity:string)=>{const value=`${action} ${entity}`.toLowerCase();if(/cash|payment|return|refund|subscription|billing/.test(value))return{key:'finance',label:'Financeiro'};if(/stock|inventory|product/.test(value))return{key:'inventory',label:'Estoque e produtos'};if(/order|checkout/.test(value))return{key:'orders',label:'Pedidos'};if(/user|access|login|permission/.test(value))return{key:'access',label:'Acessos'};if(/support|ticket/.test(value))return{key:'support',label:'Suporte'};if(/store|setting|config/.test(value))return{key:'settings',label:'Configurações'};return{key:'other',label:'Outros'};};
const actionLabel=(action:string)=>({register_store:'Loja cadastrada',create_user:'Usuário criado',create_order:'Pedido registrado',order_status_update:'Status do pedido alterado',cancel_order:'Pedido cancelado',register_return:'Devolução registrada',inventory_adjust:'Estoque ajustado',admin_subscription_update:'Assinatura alterada',support_ticket_created:'Chamado aberto'} as Record<string,string>)[action]||action.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const isCritical=(l:AuditLog)=>/cancel|refund|return|block|suspend|delete|payment|subscription/.test(`${l.action} ${l.entity}`.toLowerCase());
const when=(v:any)=>v?.toDate?.()?.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})||'Agora';
const isToday=(v:any)=>{const d=v?.toDate?.();if(!d)return false;const n=new Date();return d.getDate()===n.getDate()&&d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear();};

export function AuditPage(){
 const {profile}=useAuth();const [logs,setLogs]=useState<AuditLog[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState<Category>('all');
 useEffect(()=>{if(!profile?.storeId)return;return onSnapshot(query(collection(db,'auditLogs'),where('storeId','==',profile.storeId)),s=>setLogs(s.docs.map(d=>({id:d.id,...d.data()} as AuditLog)).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,200)));},[profile?.storeId]);
 const filtered=useMemo(()=>logs.filter(l=>{const cat=categoryInfo(l.action,l.entity).key;const q=search.trim().toLowerCase();return(category==='all'||cat===category)&&(!q||`${l.description} ${l.userName||''} ${actionLabel(l.action)}`.toLowerCase().includes(q));}),[logs,search,category]);
 const today=logs.filter(l=>isToday(l.createdAt)).length,users=new Set(logs.map(l=>l.userId).filter(Boolean)).size,critical=logs.filter(isCritical).length;
 return <><div className="page-head"><div><h1>Histórico de atividades</h1><p>Veja quem fez cada alteração importante na loja, quando aconteceu e o que foi modificado.</p></div></div>
 <div className="audit-summary-grid"><div className="audit-summary-card"><Activity/><div><small>Eventos registrados</small><strong>{logs.length}</strong><span>últimos registros</span></div></div><div className="audit-summary-card"><CalendarDays/><div><small>Atividades hoje</small><strong>{today}</strong><span>no dia atual</span></div></div><div className="audit-summary-card"><UserRound/><div><small>Responsáveis</small><strong>{users}</strong><span>usuários identificados</span></div></div><div className="audit-summary-card"><AlertTriangle/><div><small>Ações sensíveis</small><strong>{critical}</strong><span>financeiro, cancelamentos e acessos</span></div></div></div>
 <div className="panel audit-toolbar"><label className="search-box"><Search size={17}/><input placeholder="Buscar atividade ou responsável" value={search} onChange={e=>setSearch(e.target.value)}/></label><select value={category} onChange={e=>setCategory(e.target.value as Category)}><option value="all">Todas as categorias</option><option value="finance">Financeiro</option><option value="inventory">Estoque e produtos</option><option value="orders">Pedidos</option><option value="access">Acessos</option><option value="settings">Configurações</option><option value="support">Suporte</option><option value="other">Outros</option></select></div>
 <div className="panel audit-timeline-panel"><div className="panel-head"><div><h2>Linha do tempo</h2><p>{filtered.length} atividade(s) encontrada(s).</p></div><ShieldCheck size={20}/></div>{filtered.length===0?<div className="empty-state"><h3>Nenhuma atividade encontrada</h3><p>Altere a busca ou os filtros.</p></div>:filtered.map(l=>{const cat=categoryInfo(l.action,l.entity);return <div className={`audit-event ${isCritical(l)?'critical':''}`} key={l.id}><div className="audit-event-dot"/><div className="audit-event-main"><div className="audit-event-title"><strong>{actionLabel(l.action)}</strong><span className={`audit-category ${cat.key}`}>{cat.label}</span></div><p>{l.description}</p><small><b>{l.userName||'Sistema'}</b> · {when(l.createdAt)}</small></div></div>})}</div></>;
}
