import { FormEvent, useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, onSnapshot, query, serverTimestamp, updateDoc, where } from 'firebase/firestore';
import { ArrowDownCircle, ArrowUpCircle, LockKeyhole, WalletCards } from 'lucide-react';
import { db } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';
import { CashMovement, CashRegister } from '../../types/models';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function CashPage(){
 const {profile}=useAuth(); const [register,setRegister]=useState<CashRegister|null>(null),[movements,setMovements]=useState<CashMovement[]>([]);const [opening,setOpening]=useState('0');const [movement,setMovement]=useState({type:'income' as 'income'|'expense',amount:'',description:''});const [closing,setClosing]=useState('');
 useEffect(()=>{if(!profile?.storeId)return;const q=query(collection(db,'cashRegisters'),where('storeId','==',profile.storeId),where('status','==','open'));return onSnapshot(q,s=>setRegister(s.empty?null:({id:s.docs[0].id,...s.docs[0].data()} as CashRegister)));},[profile?.storeId]);
 useEffect(()=>{if(!profile?.storeId||!register?.id){setMovements([]);return;}return onSnapshot(query(collection(db,'cashMovements'),where('storeId','==',profile.storeId),where('cashRegisterId','==',register.id)),s=>setMovements(s.docs.map(d=>({id:d.id,...d.data()} as CashMovement))));},[profile?.storeId,register?.id]);
 const balance=useMemo(()=>Number(register?.openingAmount||0)+movements.reduce((s,m)=>s+(m.type==='income'?m.amount:-m.amount),0),[register,movements]);
 async function openCash(e:FormEvent){e.preventDefault();if(!profile?.storeId||!profile.uid)return;await addDoc(collection(db,'cashRegisters'),{storeId:profile.storeId,openedBy:profile.uid,status:'open',openingAmount:Number(opening||0),openedAt:serverTimestamp()});setOpening('0');}
 async function addMovement(e:FormEvent){e.preventDefault();if(!profile?.storeId||!profile.uid||!register||!movement.description.trim()||Number(movement.amount)<=0)return;await addDoc(collection(db,'cashMovements'),{storeId:profile.storeId,cashRegisterId:register.id,type:movement.type,amount:Number(movement.amount),description:movement.description.trim(),createdAt:serverTimestamp(),createdBy:profile.uid});setMovement({type:'income',amount:'',description:''});}
 async function closeCash(e:FormEvent){e.preventDefault();if(!register)return;await updateDoc(doc(db,'cashRegisters',register.id),{status:'closed',closingAmount:Number(closing||balance),closedAt:serverTimestamp()});setClosing('');}
 if(!register)return <><div className="page-head"><div><h1>Caixa</h1><p>Abra o caixa para registrar entradas, saídas e acompanhar o saldo.</p></div></div><div className="panel compact-panel"><WalletCards size={34}/><h2>Caixa fechado</h2><form onSubmit={openCash} className="inline-form"><label>Valor de abertura<input type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)}/></label><button className="primary-btn">Abrir caixa</button></form></div></>;
 return <><div className="page-head"><div><h1>Caixa</h1><p>Controle simples das movimentações do caixa aberto.</p></div><span className="status-chip ok">Caixa aberto</span></div><div className="stats"><div className="stat"><span>Abertura</span><strong>{money(register.openingAmount)}</strong></div><div className="stat"><span>Entradas</span><strong>{money(movements.filter(m=>m.type==='income').reduce((s,m)=>s+m.amount,0))}</strong></div><div className="stat"><span>Saídas</span><strong>{money(movements.filter(m=>m.type==='expense').reduce((s,m)=>s+m.amount,0))}</strong></div><div className="stat"><span>Saldo esperado</span><strong>{money(balance)}</strong></div></div><div className="two-cols"><div className="panel"><h2>Nova movimentação</h2><form onSubmit={addMovement} className="form-grid"><label>Tipo<select value={movement.type} onChange={e=>setMovement({...movement,type:e.target.value as any})}><option value="income">Entrada / suprimento</option><option value="expense">Saída / sangria</option></select></label><label>Valor<input type="number" min="0.01" step="0.01" value={movement.amount} onChange={e=>setMovement({...movement,amount:e.target.value})}/></label><label className="span-2">Descrição<input placeholder="Motivo da movimentação" value={movement.description} onChange={e=>setMovement({...movement,description:e.target.value})}/></label><button className="primary-btn">Registrar</button></form></div><div className="panel"><h2>Fechar caixa</h2><p>Saldo esperado agora: <strong>{money(balance)}</strong></p><form onSubmit={closeCash} className="inline-form"><input type="number" min="0" step="0.01" placeholder={String(balance)} value={closing} onChange={e=>setClosing(e.target.value)}/><button className="secondary-btn"><LockKeyhole size={17}/>Fechar caixa</button></form></div></div><div className="panel"><h2>Movimentações</h2><div className="movement-list">{movements.length===0?<p className="muted">Nenhuma movimentação manual.</p>:movements.map(m=><div className="movement-row" key={m.id}><span className={m.type==='income'?'movement-icon income':'movement-icon expense'}>{m.type==='income'?<ArrowUpCircle/>:<ArrowDownCircle/>}</span><div><strong>{m.description}</strong><small>{m.type==='income'?'Entrada':'Saída'}</small></div><b>{m.type==='income'?'+':'-'} {money(m.amount)}</b></div>)}</div></div></>;
}
