import { FormEvent, useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, onSnapshot, query, serverTimestamp, updateDoc, where } from 'firebase/firestore';
import { db } from '../../lib/firebase'; import { useAuth } from '../../contexts/AuthContext'; import { Coupon } from '../../types/models';
export function CouponsPage(){
 const {profile}=useAuth();const [items,setItems]=useState<Coupon[]>([]);
 const [form,setForm]=useState({code:'',type:'percent',value:'10',minOrder:''});
 useEffect(()=>{if(!profile?.storeId)return;return onSnapshot(query(collection(db,'coupons'),where('storeId','==',profile.storeId)),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()} as Coupon))));},[profile?.storeId]);
 async function create(e:FormEvent){e.preventDefault();if(!profile?.storeId||!form.code.trim())return;const value=Number(form.value.replace(',','.'));const minOrder=form.minOrder.trim()===''?0:Number(form.minOrder.replace(',','.'));if(!Number.isFinite(value)||value<0||!Number.isFinite(minOrder)||minOrder<0)return;await addDoc(collection(db,'coupons'),{storeId:profile.storeId,code:form.code.trim().toUpperCase(),type:form.type,value,minOrder,active:true,uses:0,createdAt:serverTimestamp()});setForm({code:'',type:'percent',value:'10',minOrder:''});}
 return <><div className="page-head"><div><h1>Cupons</h1><p>Crie incentivos para aumentar conversão e ticket médio.</p></div></div><div className="panel"><form onSubmit={create} className="form-grid"><label>Código<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="BEMVINDO10"/></label><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select></label><label>Desconto<input type="number" min="0" step="0.01" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></label><label>Pedido mínimo<input type="number" min="0" step="0.01" value={form.minOrder} onChange={e=>setForm({...form,minOrder:e.target.value})} placeholder="0,00"/></label><button className="primary-btn">Criar cupom</button></form></div><div className="table-card"><table><thead><tr><th>Código</th><th>Desconto</th><th>Mínimo</th><th>Status</th><th></th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><strong>{c.code}</strong></td><td>{c.type==='percent'?`${c.value}%`:`R$ ${c.value.toFixed(2)}`}</td><td>R$ {Number(c.minOrder||0).toFixed(2)}</td><td><button className="secondary-btn" onClick={()=>updateDoc(doc(db,'coupons',c.id),{active:!c.active})}>{c.active?'Ativo':'Inativo'}</button></td><td><button className="secondary-btn" onClick={()=>deleteDoc(doc(db,'coupons',c.id))}>Excluir</button></td></tr>)}</tbody></table></div></>;
}
