import { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, getDoc, serverTimestamp } from 'firebase/firestore';
import QRCode from 'qrcode';
import { CreditCard, QrCode, ShieldCheck, WalletCards, MessageCircle, Copy } from 'lucide-react';
import { db } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';
import { buildPixPayload } from '../../lib/pix';

type StoreSettings={id?:string;name?:string;checkoutMode?:'whatsapp'|'online'|'both';paymentProviderConnected?:boolean;};
type Billing={pixKey?:string;pixName?:string;pixCity?:string;billingWhatsapp?:string;monthlyPrice?:number;};

export function PaymentsPage(){
 const {profile}=useAuth();const [store,setStore]=useState<StoreSettings|null>(null),[billing,setBilling]=useState<Billing>({}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[qr,setQr]=useState(''),[tab,setTab]=useState<'sales'|'subscription'>('sales');
 useEffect(()=>{(async()=>{if(!profile?.storeId){setLoading(false);return;}try{const s=await getDoc(doc(db,'stores',profile.storeId));setStore(s.exists()?({id:s.id,...s.data()} as StoreSettings):null);try{const b=await getDoc(doc(db,'platformSettings','billing'));setBilling(b.exists()?b.data() as Billing:{});}catch{setBilling({billingWhatsapp:'88888499692'});}}catch(e:any){setMessage(String(e?.message||'Não foi possível carregar os dados da loja.').replace('FirebaseError: ',''));}finally{setLoading(false)}})()},[profile?.storeId]);
 const amount=useMemo(()=>Number(billing.monthlyPrice||0),[billing.monthlyPrice]);
 const payload=useMemo(()=>billing.pixKey&&amount>0?buildPixPayload({key:billing.pixKey,name:billing.pixName||'VITRIO',city:billing.pixCity||'QUIXERAMOBIM',amount,txid:`VITRIO${profile?.storeId?.slice(0,12)||''}`}):'',[billing,amount,profile?.storeId]);
 useEffect(()=>{if(!payload){setQr('');return}QRCode.toDataURL(payload,{width:320,margin:2}).then(setQr)},[payload]);
 async function notifyPayment(){if(!profile?.storeId||!store)return;await addDoc(collection(db,'subscriptionPayments'),{storeId:profile.storeId,storeName:store.name||'',plan:'monthly',amount,status:'awaiting_review',createdAt:serverTimestamp(),createdBy:profile.uid});const phone=(billing.billingWhatsapp||'').replace(/\D/g,'');const text=encodeURIComponent(`Olá! Sou da loja ${store.name||profile.storeId}. Efetuei o pagamento da assinatura mensal Vitrio no valor de R$ ${amount.toFixed(2)}. Vou enviar o comprovante nesta conversa para conferência.`);if(phone)window.location.href=`https://wa.me/${phone}?text=${text}`;else setMessage('O responsável pela plataforma ainda não configurou o WhatsApp para conferência.')}
 if(loading)return <div className="panel">Carregando pagamentos...</div>;if(!store)return <div className="panel">Loja não encontrada.</div>;
 return <><div className="page-head"><div><h1>Pagamentos</h1><p>Separe os recebimentos das suas vendas do pagamento da assinatura Vitrio.</p></div></div>
 <div className="payment-tabs"><button className={tab==='sales'?'active':''} onClick={()=>setTab('sales')}><WalletCards/> Recebimentos da loja</button><button className={tab==='subscription'?'active':''} onClick={()=>setTab('subscription')}><QrCode/> Assinatura Vitrio</button></div>
 {message&&<div className="notice">{message}</div>}
 {tab==='sales'?<div className="payment-layout"><section className="panel payment-hero"><CreditCard/><div><h2>Recebimentos da sua loja</h2><p>Nesta versão, o cliente escolhe a forma de pagamento e o pedido é concluído pelo WhatsApp. O Vitrio não movimenta o dinheiro das vendas.</p></div><span className="status-chip">WhatsApp</span></section><section className="panel"><h2>Pagamento integrado</h2><p>A conexão automática com meios de pagamento ficará disponível futuramente. Até lá, Pix, cartão e dinheiro são acertados diretamente entre a loja e o cliente.</p><div className="connection-tip"><ShieldCheck/><div><strong>Separação financeira</strong><p>A mensalidade do Vitrio continua separada do faturamento das suas vendas.</p></div></div></section></div>:
 <div className="payment-layout"><section className="panel subscription-pay-card"><div><span className="eyebrow">ASSINATURA MENSAL</span><h2>{amount.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</h2><p>Pagamento da assinatura da plataforma Vitrio.</p></div>{qr?<img src={qr} alt="QR Code Pix da assinatura"/>:<div className="qr-placeholder">Pix ainda não configurado pelo responsável pela plataforma.</div>}<button className="secondary-btn" disabled={!payload} onClick={()=>navigator.clipboard.writeText(payload)}><Copy/> Copiar Pix copia e cola</button></section><section className="panel"><h2>Como confirmar o pagamento</h2><div className="billing-steps"><div><b>1</b><span>Escaneie o QR Code ou copie o código Pix.</span></div><div><b>2</b><span>Confira o valor da mensalidade.</span></div><div><b>3</b><span>Após pagar, clique abaixo e envie o comprovante no WhatsApp.</span></div></div><button className="primary-btn" disabled={!payload||!billing.billingWhatsapp} onClick={notifyPayment}><MessageCircle/> Paguei — enviar comprovante</button><small className="muted">A ativação/renovação acontece após a conferência do responsável pela plataforma.</small></section></div>}
 </>;
}
