import { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot, query, where } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';
import { Order } from '../../types/models';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function ReportsPage(){const {profile}=useAuth();const [orders,setOrders]=useState<Order[]>([]),[period,setPeriod]=useState('30');
useEffect(()=>{if(!profile?.storeId)return;return onSnapshot(query(collection(db,'orders'),where('storeId','==',profile.storeId)),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()} as Order))));},[profile?.storeId]);
const filtered=useMemo(()=>{const days=Number(period);if(!days)return orders;const cutoff=new Date();cutoff.setDate(cutoff.getDate()-days);cutoff.setHours(0,0,0,0);return orders.filter(o=>{const d=o.createdAt?.toDate?.();return d&&d>=cutoff})},[orders,period]);
const valid=filtered.filter(o=>o.status!=='cancelled'),paid=valid.filter(o=>o.paymentStatus==='paid'),revenue=paid.reduce((s,o)=>s+o.total,0),ticket=paid.length?revenue/paid.length:0,discounts=valid.reduce((s,o)=>s+Number(o.discount||0),0),delivery=valid.reduce((s,o)=>s+Number(o.deliveryFee||0),0);
const productMap=new Map<string,{name:string,qty:number,total:number}>();valid.forEach(o=>o.items.forEach(i=>{const v=productMap.get(i.productId)||{name:i.name,qty:0,total:0};v.qty+=i.quantity;v.total+=i.subtotal;productMap.set(i.productId,v)}));const top=[...productMap.values()].sort((a,b)=>b.qty-a.qty).slice(0,8);
function exportCsv(){const rows=[['Pedido','Data','Cliente','Pagamento','Status','Subtotal','Desconto','Entrega','Total'],...filtered.map(o=>[o.id,o.createdAt?.toDate?.()?.toLocaleString('pt-BR')||'',o.customerName,o.paymentMethod,o.status,o.subtotal,o.discount||0,o.deliveryFee||0,o.total])];const csv=rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob([`\ufeff${csv}`],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`vitrio-relatorio-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
const methods=[...valid.reduce((m,o)=>{m.set(o.paymentMethod,(m.get(o.paymentMethod)||0)+1);return m},new Map<string,number>()).entries()].sort((a,b)=>b[1]-a[1]);
return <><div className="page-head"><div><h1>Relatórios</h1><p>Analise vendas e operação por período.</p></div><div className="report-actions"><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="0">Todo período</option></select></label><button className="secondary-btn" onClick={exportCsv}>Exportar CSV</button></div></div><div className="stats"><div className="stat"><span>Pedidos</span><strong>{valid.length}</strong></div><div className="stat"><span>Pedidos pagos</span><strong>{paid.length}</strong></div><div className="stat"><span>Faturamento pago</span><strong>{money(revenue)}</strong></div><div className="stat"><span>Ticket médio</span><strong>{money(ticket)}</strong></div><div className="stat"><span>Descontos</span><strong>{money(discounts)}</strong></div><div className="stat"><span>Taxas de entrega</span><strong>{money(delivery)}</strong></div></div><div className="two-cols"><div className="panel"><h2>Produtos mais pedidos</h2>{top.length===0?<p className="muted">Ainda não há dados suficientes.</p>:<div className="ranking-list">{top.map((p,i)=><div key={p.name}><span>{i+1}</span><div><strong>{p.name}</strong><small>{p.qty} unidade(s)</small></div><b>{money(p.total)}</b></div>)}</div>}</div><div className="panel"><h2>Formas de pagamento</h2>{methods.length===0?<p className="muted">Sem dados.</p>:methods.map(([name,count])=><div className="mini-row" key={name}><strong>{name}</strong><b>{count} pedido(s)</b></div>)}</div></div></>;}
