import { FormEvent, useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot, query, where } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { Archive, CheckCircle2, PackageCheck, RotateCcw, Search, WalletCards } from 'lucide-react';
import { db, functions } from '../../lib/firebase';
import { useAuth } from '../../contexts/AuthContext';
import { Order, ReturnRecord } from '../../types/models';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const when=(v:any)=>v?.toDate?.()?.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})||'—';

export function ReturnsPage(){
 const {profile}=useAuth();const [orders,setOrders]=useState<Order[]>([]),[returns,setReturns]=useState<ReturnRecord[]>([]);
 const [orderId,setOrderId]=useState(''),[type,setType]=useState<'return'|'exchange'>('return'),[reason,setReason]=useState(''),[qtys,setQtys]=useState<Record<string,number>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[historySearch,setHistorySearch]=useState('');
 useEffect(()=>{if(!profile?.storeId)return;const a=onSnapshot(query(collection(db,'orders'),where('storeId','==',profile.storeId)),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()} as Order)).filter(o=>o.status!=='cancelled').sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0))));const b=onSnapshot(query(collection(db,'returns'),where('storeId','==',profile.storeId)),s=>setReturns(s.docs.map(d=>({id:d.id,...d.data()} as ReturnRecord)).sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0))));return()=>{a();b();}},[profile?.storeId]);
 const order=useMemo(()=>orders.find(o=>o.id===orderId),[orders,orderId]);
 const priorByIndex=useMemo(()=>{const m=new Map<number,number>();returns.filter(r=>r.orderId===orderId).forEach(r=>r.items.forEach(i=>{if(Number.isInteger(i.orderItemIndex))m.set(i.orderItemIndex!,Number(m.get(i.orderItemIndex!)||0)+Number(i.quantity||0))}));return m},[returns,orderId]);
 const selectedTotal=useMemo(()=>!order?0:order.items.reduce((sum,i,index)=>sum+Number(qtys[String(index)]||0)*Number(i.price||0),0),[order,qtys]);
 const history=useMemo(()=>{const q=historySearch.trim().toLowerCase();return returns.filter(r=>!q||`${r.orderId} ${r.customerName||''} ${r.reason||''} ${r.items.map(i=>i.name).join(' ')}`.toLowerCase().includes(q))},[returns,historySearch]);
 async function submit(e:FormEvent){e.preventDefault();setMessage('');if(!order)return;const items=order.items.map((i,index)=>({orderItemIndex:index,productId:i.productId,variantId:i.variantId||'',quantity:Number(qtys[String(index)]||0)})).filter(i=>i.quantity>0);if(!items.length){setMessage('Selecione ao menos um item e informe a quantidade.');return;}if(!reason.trim()){setMessage('Informe o motivo da troca/devolução.');return;}setBusy(true);try{const fn=httpsCallable(functions,'registerReturn');const res:any=await fn({orderId:order.id,type,reason:reason.trim(),items});setMessage(`${type==='exchange'?'Troca':'Devolução'} registrada com sucesso: ${money(Number(res.data.total||0))}. Estoque atualizado${res.data.financialApplied?' e estorno lançado no caixa':''}.`);setQtys({});setReason('');setOrderId('');}catch(e:any){setMessage(e?.message?.replace('FirebaseError: ','')||'Não foi possível registrar.');}finally{setBusy(false)}}
 return <><div className="page-head"><div><h1>Trocas e devoluções</h1><p>Selecione o pedido, escolha exatamente o que retornou e mantenha estoque, caixa e histórico consistentes.</p></div></div>
 <div className="panel return-operation-panel"><form onSubmit={submit} className="form-grid"><label>Pedido<select value={orderId} onChange={e=>{setOrderId(e.target.value);setQtys({});setMessage('')}} required><option value="">Selecione um pedido...</option>{orders.map(o=><option value={o.id} key={o.id}>#{o.id.slice(0,6).toUpperCase()} · {o.customerName} · {money(o.total)}</option>)}</select></label><label>Operação<select value={type} onChange={e=>setType(e.target.value as any)}><option value="return">Devolução / estorno</option><option value="exchange">Troca</option></select></label>
 {order&&<div className="span-2 return-order-summary"><div><small>Cliente</small><strong>{order.customerName}</strong></div><div><small>Pedido</small><strong>#{order.id.slice(0,6).toUpperCase()}</strong></div><div><small>Pagamento</small><strong>{order.paymentMethod}</strong></div><div><small>Total original</small><strong>{money(order.total)}</strong></div></div>}
 {order&&<div className="span-2 return-items"><div className="return-section-title"><div><strong>Itens comprados</strong><small>Informe somente a quantidade que será devolvida.</small></div><PackageCheck size={20}/></div>{order.items.map((i,index)=>{const returned=Number(priorByIndex.get(index)||0),available=Math.max(0,Number(i.quantity||0)-returned),key=String(index);return <label key={`${i.productId}-${i.variantId||''}-${index}`} className={available<=0?'return-item-disabled':''}><div><strong>{i.name}{i.variantName?` · ${i.variantName}`:''}</strong><small>{money(i.price)} cada · Comprado: {i.quantity}{returned?` · Já devolvido: ${returned}`:''}</small></div><input type="number" min="0" max={available} disabled={available<=0} value={qtys[key]||0} onChange={e=>setQtys({...qtys,[key]:Math.min(available,Math.max(0,Number(e.target.value)))})}/><small>Disponível para devolver: {available}</small></label>})}</div>}
 {order&&<div className="span-2 return-refund-summary"><RotateCcw size={20}/><div><small>{type==='return'?'Valor do estorno':'Valor dos itens da troca'}</small><strong>{money(selectedTotal)}</strong></div>{type==='return'&&<span>Pedido pago: o valor será lançado como saída no caixa aberto.</span>}</div>}
 <label className="span-2">Motivo / observação<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Descreva o motivo. Ex.: peça rasgada, tamanho incorreto, defeito..."/></label><button className="primary-btn" disabled={busy||!order}>{busy?'Registrando...':'Registrar operação'}</button>{message&&<p className="span-2 return-message">{message}</p>}</form></div>
 <div className="panel return-history-panel"><div className="panel-head"><div><h2>Histórico arquivado</h2><p>Registro permanente para consultas e relatórios.</p></div><label className="search-box"><Search size={17}/><input placeholder="Buscar no histórico" value={historySearch} onChange={e=>setHistorySearch(e.target.value)}/></label></div>{history.length===0?<div className="empty-state"><Archive size={28}/><h3>Nenhum registro</h3><p>As trocas e devoluções aparecerão aqui.</p></div>:history.map(r=><div className="return-history-row" key={r.id}><div className="return-history-icon"><CheckCircle2 size={18}/></div><div className="return-history-copy"><strong>{r.type==='exchange'?'Troca':'Devolução'} · #{r.orderId.slice(0,6).toUpperCase()} {r.customerName?`· ${r.customerName}`:''}</strong><small>{r.items.map(i=>`${i.quantity}x ${i.name}${i.variantName?` (${i.variantName})`:''}`).join(' · ')}</small><span>{when(r.createdAt)} · Motivo: {r.reason||'Não informado'}</span></div><div className="return-history-value"><b>{money(r.total)}</b><small>{r.financialApplied?<><WalletCards size={13}/> Estornado no caixa</>:'Estoque atualizado'}</small></div></div>)}</div></>;
}
