import { useEffect, useMemo, useState } from 'react';
import { collection, doc, onSnapshot, query, where } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { useAuth } from '../contexts/AuthContext';
import { Order, Product, Store } from '../types/models';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowRight, CheckCircle2, Circle, DollarSign, MailWarning, PackagePlus, Rocket, ShoppingCart, Store as StoreIcon, TrendingUp, Users } from 'lucide-react';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function DashboardPage(){
 const {profile,firebaseUser}=useAuth(); const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[store,setStore]=useState<Store|null>(null);
 useEffect(()=>{if(!profile?.storeId)return;const a=onSnapshot(query(collection(db,'products'),where('storeId','==',profile.storeId)),s=>setProducts(s.docs.map(d=>({id:d.id,...d.data()} as Product))));const b=onSnapshot(query(collection(db,'orders'),where('storeId','==',profile.storeId)),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()} as Order))));const c=onSnapshot(doc(db,'stores',profile.storeId),s=>setStore(s.exists()?({id:s.id,...s.data()} as Store):null));return()=>{a();b();c()}},[profile?.storeId]);
 const data=useMemo(()=>{const now=new Date(),startToday=new Date(now);startToday.setHours(0,0,0,0);const startWeek=new Date(startToday);startWeek.setDate(startToday.getDate()-6);const paid=orders.filter(o=>o.paymentStatus==='paid');const todayOrders=orders.filter(o=>{const d=o.createdAt?.toDate?.();return d&&d>=startToday&&o.status!=='cancelled'});const todayPaid=todayOrders.filter(o=>o.paymentStatus==='paid');const weekPaid=paid.filter(o=>{const d=o.createdAt?.toDate?.();return d&&d>=startWeek});const revenue=todayPaid.reduce((s,o)=>s+o.total,0);const weekRevenue=weekPaid.reduce((s,o)=>s+o.total,0);const ticket=weekPaid.length?weekRevenue/weekPaid.length:0;const awaiting=orders.filter(o=>!['completed','cancelled'].includes(o.status)).length;const low=products.filter(p=>p.stock<=5).length;const top=new Map<string,{name:string,qty:number,total:number}>();weekPaid.forEach(o=>o.items.forEach(i=>{const v=top.get(i.productId)||{name:i.name,qty:0,total:0};v.qty+=i.quantity;v.total+=i.subtotal;top.set(i.productId,v)}));const topProducts=[...top.values()].sort((a,b)=>b.qty-a.qty).slice(0,4);const days=[...Array(7)].map((_,i)=>{const d=new Date(startToday);d.setDate(startToday.getDate()-(6-i));return d});const series=days.map(d=>{const end=new Date(d);end.setDate(d.getDate()+1);const os=paid.filter(o=>{const x=o.createdAt?.toDate?.();return x&&x>=d&&x<end});return{label:d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),value:os.reduce((s,o)=>s+o.total,0)}});return{todayOrders:todayOrders.length,revenue,weekRevenue,ticket,awaiting,low,topProducts,series}},[orders,products]);
 const max=Math.max(...data.series.map(x=>x.value),1); const monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);const prevMonthStart=new Date(monthStart);prevMonthStart.setMonth(prevMonthStart.getMonth()-1);const monthRevenue=orders.filter(o=>o.paymentStatus==='paid'&&o.status!=='cancelled'&&o.createdAt?.toDate?.()>=monthStart).reduce((sum,o)=>sum+Number(o.total||0),0);const prevMonthRevenue=orders.filter(o=>{const d=o.createdAt?.toDate?.();return o.paymentStatus==='paid'&&o.status!=='cancelled'&&d&&d>=prevMonthStart&&d<monthStart}).reduce((sum,o)=>sum+Number(o.total||0),0);const monthDelta=prevMonthRevenue?Math.round((monthRevenue-prevMonthRevenue)/prevMonthRevenue*100):null;const monthlyGoal=Number(store?.monthlySalesGoal||0);const goalPct=monthlyGoal?Math.min(100,Math.round(monthRevenue/monthlyGoal*100)):0; const setup=[{done:!!store?.onboardingCompleted,label:'Informações básicas',to:'/painel/primeiros-passos'},{done:products.length>0,label:'Primeiro produto cadastrado',to:'/painel/produtos'},{done:!!store?.logoUrl,label:'Identidade visual configurada',to:'/painel/minha-loja'}];const setupDone=setup.filter(x=>x.done).length;
 const greeting=new Date().getHours()<12?'Bom dia':new Date().getHours()<18?'Boa tarde':'Boa noite';
 return <><div className="dashboard-welcome"><div><span>{greeting}</span><h1>{profile?.displayName?.split(' ')[0]||'Lojista'}, sua loja em um só lugar.</h1><p>Acompanhe vendas, pedidos e pendências sem precisar procurar em várias telas.</p></div><div className="quick-actions"><Link to="/painel/produtos"><PackagePlus size={18}/><span>Novo produto</span></Link><Link to="/painel/pedidos"><ShoppingCart size={18}/><span>Ver pedidos</span></Link><a href={store?`/loja/${store.slug}`:'#'} target="_blank" rel="noreferrer"><StoreIcon size={18}/><span>Abrir vitrine</span></a></div></div>
 {(!firebaseUser?.emailVerified||setupDone<setup.length)&&<div className="dashboard-guidance">{!firebaseUser?.emailVerified&&<Link to="/verificar-email" className="guidance-card warning"><MailWarning/><div><strong>Confirme seu e-mail</strong><small>Proteja a conta e facilite a recuperação de acesso.</small></div></Link>}<div className="guidance-card"><Rocket/><div><strong>Configuração da loja · {setupDone}/{setup.length}</strong><div className="mini-checks">{setup.map(x=><Link key={x.label} to={x.to}>{x.done?<CheckCircle2/>:<Circle/>}{x.label}</Link>)}</div></div></div></div>}
 <div className="metric-grid clean-metrics"><div className="metric-card accent"><span><DollarSign/>Faturamento hoje</span><strong>{money(data.revenue)}</strong><small>{data.todayOrders} pedido(s) hoje · mês {money(monthRevenue)}{monthDelta!==null?` (${monthDelta>=0?'+':''}${monthDelta}% vs. anterior)`:''}</small></div><div className="metric-card"><span><TrendingUp/>Últimos 7 dias</span><strong>{money(data.weekRevenue)}</strong><small>Ticket médio {money(data.ticket)}</small></div><div className="metric-card"><span><ShoppingCart/>Em andamento</span><strong>{data.awaiting}</strong><small>Pedidos que pedem acompanhamento</small></div><div className="metric-card"><span><AlertTriangle/>Estoque baixo</span><strong>{data.low}</strong><small>{data.low?'Vale revisar a reposição':'Tudo sob controle'}</small></div></div>
 {monthlyGoal>0&&<section className="panel sales-goal-card"><div className="panel-head"><div><h2>Meta do mês</h2><p className="panel-subtitle">{money(monthRevenue)} de {money(monthlyGoal)}</p></div><strong>{goalPct}%</strong></div><div className="goal-progress"><span style={{width:`${goalPct}%`}}/></div><small>{monthRevenue>=monthlyGoal?'Meta alcançada. Excelente ritmo!':`Faltam ${money(Math.max(0,monthlyGoal-monthRevenue))} para chegar à meta.`}</small></section>}
 <div className="dashboard-main-grid"><section className="panel chart-panel"><div className="panel-head"><div><h2>Vendas da semana</h2><p className="panel-subtitle">Receita confirmada nos últimos 7 dias</p></div><Link to="/painel/relatorios">Relatórios <ArrowRight size={14}/></Link></div><div className="bar-chart modern">{data.series.map(x=><div className="bar-col" key={x.label}><div className="bar-value">{x.value?money(x.value):'—'}</div><div className="bar-track"><div className="bar-fill" style={{height:`${Math.max(5,(x.value/max)*100)}%`}}/></div><small>{x.label}</small></div>)}</div></section>
 <section className="panel smart-panel"><div className="panel-head"><div><h2>Resumo inteligente</h2><p className="panel-subtitle">Prioridades para agora</p></div></div><div className="smart-list"><Link to="/painel/pedidos" className={data.awaiting?'needs-attention':'is-ok'}>{data.awaiting?<AlertTriangle/>:<CheckCircle2/>}<div><strong>{data.awaiting?`${data.awaiting} pedido(s) em andamento`:'Pedidos em dia'}</strong><small>{data.awaiting?'Acompanhe preparo, entrega e conclusão.':'Nenhuma pendência operacional.'}</small></div><ArrowRight/></Link><Link to="/painel/estoque" className={data.low?'needs-attention':'is-ok'}>{data.low?<AlertTriangle/>:<CheckCircle2/>}<div><strong>{data.low?`${data.low} produto(s) com estoque baixo`:'Estoque saudável'}</strong><small>{data.low?'Evite perder vendas por ruptura.':'Nenhuma reposição urgente.'}</small></div><ArrowRight/></Link><Link to="/painel/clientes" className="is-neutral"><Users/><div><strong>Cuide da sua base de clientes</strong><small>Use histórico de compras para vender novamente.</small></div><ArrowRight/></Link></div></section></div>
 <div className="two-cols"><section className="panel"><div className="panel-head"><h2>Pedidos recentes</h2><Link to="/painel/pedidos">Ver todos</Link></div>{orders.length===0?<p className="muted">Nenhum pedido registrado ainda.</p>:orders.slice().sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,5).map(o=><div className="mini-row richer" key={o.id}><div><strong>#{o.id.slice(0,6).toUpperCase()} · {o.customerName}</strong><small>{o.items.reduce((s,i)=>s+i.quantity,0)} item(ns) · {o.paymentStatus==='paid'?'Pago':'Pagamento pendente'}</small></div><b>{money(o.total)}</b></div>)}</section><section className="panel"><div className="panel-head"><h2>Produtos que mais saem</h2><Link to="/painel/produtos">Catálogo</Link></div>{data.topProducts.length===0?<p className="muted">Os campeões de venda aparecerão aqui.</p>:data.topProducts.map((p,i)=><div className="mini-row ranking" key={p.name}><span>{i+1}</span><div><strong>{p.name}</strong><small>{p.qty} unidade(s) vendida(s)</small></div><b>{money(p.total)}</b></div>)}</section></div></>;
}
