import { useEffect, useMemo, useState } from 'react';
import { collection, limit, onSnapshot, orderBy, query } from 'firebase/firestore';
import { Activity, AlertTriangle, Building2, Search, ShieldCheck, UserRound } from 'lucide-react';
import { db } from '../../lib/firebase';
import { AuditLog } from '../../types/models';

type Category='all'|'finance'|'inventory'|'orders'|'access'|'settings'|'support'|'other';
const categoryInfo=(action:string,entity:string)=>{const value=`${action} ${entity}`.toLowerCase();if(/cash|payment|return|refund|subscription|billing/.test(value))return{key:'finance',label:'Financeiro'};if(/stock|inventory|product/.test(value))return{key:'inventory',label:'Estoque e produtos'};if(/order|checkout/.test(value))return{key:'orders',label:'Pedidos'};if(/user|access|login|permission/.test(value))return{key:'access',label:'Acessos'};if(/support|ticket/.test(value))return{key:'support',label:'Suporte'};if(/store|setting|config/.test(value))return{key:'settings',label:'Configurações'};return{key:'other',label:'Outros'};};
const actionLabel=(action:string)=>({register_store:'Loja cadastrada',create_user:'Usuário criado',create_order:'Pedido registrado',order_status_update:'Status do pedido alterado',cancel_order:'Pedido cancelado',register_return:'Devolução registrada',inventory_adjust:'Estoque ajustado',admin_subscription_update:'Assinatura alterada',support_ticket_created:'Chamado aberto',create_support_ticket:'Chamado aberto',answer_support_ticket:'Chamado respondido',update_order:'Pedido atualizado',whatsapp_sale:'Venda pelo WhatsApp'} as Record<string,string>)[action]||action.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const isCritical=(l:AuditLog)=>/cancel|refund|return|block|suspend|delete|payment|subscription/.test(`${l.action} ${l.entity}`.toLowerCase());
const date=(v:any)=>{try{return v?.toDate?.().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})||'—'}catch{return'—'}};

export function AdminAuditPage(){
 const [logs,setLogs]=useState<AuditLog[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState<Category>('all');
 useEffect(()=>onSnapshot(query(collection(db,'auditLogs'),orderBy('createdAt','desc'),limit(250)),s=>setLogs(s.docs.map(d=>({id:d.id,...d.data()} as AuditLog)))),[]);
 const filtered=useMemo(()=>logs.filter(l=>{const cat=categoryInfo(l.action,l.entity).key,q=search.trim().toLowerCase();return(category==='all'||cat===category)&&(!q||`${l.description} ${l.userName||''} ${l.storeId||''} ${actionLabel(l.action)}`.toLowerCase().includes(q));}),[logs,search,category]);
 const humanLogs=logs.filter(l=>String(l.userId||'').toLowerCase()!=='system'&&!/checkout whatsapp|sistema/i.test(String(l.userName||'')));
 const stores=new Set(logs.map(l=>l.storeId).filter(Boolean)).size,users=new Set(humanLogs.map(l=>l.userId||l.userName).filter(Boolean)).size,critical=logs.filter(isCritical).length;
 return <><div className="page-head"><div><h1>Auditoria da plataforma</h1><p>Rastreie ações administrativas e operacionais importantes em todas as lojas.</p></div></div>
 <div className="audit-summary-grid"><div className="audit-summary-card"><Activity/><div><small>Eventos registrados</small><strong>{logs.length}</strong><span>janela recente</span></div></div><div className="audit-summary-card"><Building2/><div><small>Lojas afetadas</small><strong>{stores}</strong><span>com atividade registrada</span></div></div><div className="audit-summary-card"><UserRound/><div><small>Responsáveis</small><strong>{users}</strong><span>usuários identificados</span></div></div><div className="audit-summary-card"><AlertTriangle/><div><small>Eventos sensíveis</small><strong>{critical}</strong><span>merecem atenção</span></div></div></div>
 <div className="panel audit-toolbar"><label className="search-box"><Search size={17}/><input placeholder="Buscar loja, usuário ou atividade" value={search} onChange={e=>setSearch(e.target.value)}/></label><select value={category} onChange={e=>setCategory(e.target.value as Category)}><option value="all">Todas as categorias</option><option value="finance">Financeiro</option><option value="inventory">Estoque e produtos</option><option value="orders">Pedidos</option><option value="access">Acessos</option><option value="settings">Configurações</option><option value="support">Suporte</option><option value="other">Outros</option></select></div>
 <div className="table-card audit-admin-table"><div className="panel-head"><div><h2>Registro de atividades</h2><p>{filtered.length} evento(s) no filtro atual.</p></div><ShieldCheck size={20}/></div><table><thead><tr><th>Data</th><th>Responsável</th><th>Loja</th><th>Categoria</th><th>Ação</th><th>Detalhes</th></tr></thead><tbody>{filtered.map(l=>{const cat=categoryInfo(l.action,l.entity);return <tr className={isCritical(l)?'audit-critical-row':''} key={l.id}><td>{date(l.createdAt)}</td><td><strong>{String(l.userId||'').toLowerCase()==='system'?'Automação do sistema':(l.userName||'Sistema')}</strong></td><td>{l.storeId||'Plataforma'}</td><td><span className={`audit-category ${cat.key}`}>{cat.label}</span></td><td>{actionLabel(l.action)}</td><td>{l.description}</td></tr>})}</tbody></table>{filtered.length===0&&<div className="empty-admin">Nenhum registro encontrado para os filtros selecionados.</div>}</div></>;
}
