import { useEffect,useMemo,useState } from 'react';
import { collection,onSnapshot } from 'firebase/firestore';
import { AlertTriangle, ArrowRight, Building2, CheckCircle2, Clock3, Headphones, ShieldAlert, Store as StoreIcon, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { db } from '../../lib/firebase';
import { AppUser,Store } from '../../types/models';
function toDate(v:any){if(!v)return null;if(typeof v?.toDate==='function')return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
export function AdminDashboardPage(){
 const [stores,setStores]=useState<Store[]>([]),[users,setUsers]=useState<AppUser[]>([]);
 useEffect(()=>{const a=onSnapshot(collection(db,'stores'),s=>setStores(s.docs.map(d=>({id:d.id,...d.data()} as Store))));const b=onSnapshot(collection(db,'users'),s=>setUsers(s.docs.map(d=>({uid:d.id,...d.data()} as AppUser))));return()=>{a();b()}},[]);
 const m=useMemo(()=>{const now=Date.now();const active=stores.filter(s=>s.active&&s.subscriptionStatus==='active').length;const trial=stores.filter(s=>s.subscriptionStatus==='trial'&&(toDate(s.trialEndsAt)?.getTime()||Infinity)>=now).length;const expiredTrial=stores.filter(s=>s.subscriptionStatus==='trial'&&(toDate(s.trialEndsAt)?.getTime()||Infinity)<now).length;const blocked=stores.filter(s=>!s.active||['suspended','cancelled'].includes(s.subscriptionStatus||'')).length;const overdue=stores.filter(s=>s.subscriptionStatus==='past_due').length;const merchants=users.filter(u=>u.role==='merchant').length;const onboarding=stores.filter(s=>s.onboardingCompleted===true).length;return{active,trial,expiredTrial,blocked,overdue,merchants,onboarding,attention:expiredTrial+blocked+overdue}},[stores,users]);
 const recent=stores.slice().sort((a:any,b:any)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,6);
 const attention=stores.filter(s=>{const exp=s.subscriptionStatus==='trial'&&(toDate(s.trialEndsAt)?.getTime()||Infinity)<Date.now();return exp||!s.active||['past_due','suspended','cancelled'].includes(s.subscriptionStatus||'')}).slice(0,6);
 return <><div className="dashboard-welcome admin-welcome"><div><span>Painel Master</span><h1>Visão clara da operação do Vitrio.</h1><p>Acompanhe crescimento, clientes que precisam de atenção e saúde da plataforma.</p></div><div className="quick-actions"><Link to="/admin/lojas"><Building2/><span>Gerenciar lojas</span></Link><Link to="/admin/acessos"><Users/><span>Gerenciar acessos</span></Link><Link to="/admin/auditoria"><ShieldAlert/><span>Ver auditoria</span></Link></div></div>
 <div className="metric-grid clean-metrics"><div className="metric-card accent"><span><StoreIcon/>Lojas cadastradas</span><strong>{stores.length}</strong><small>{m.active} assinatura(s) ativa(s)</small></div><div className="metric-card"><span><Users/>Lojistas</span><strong>{m.merchants}</strong><small>{m.onboarding} onboarding(s) concluído(s)</small></div><div className="metric-card"><span><Clock3/>Em teste</span><strong>{m.trial}</strong><small>{m.expiredTrial} teste(s) vencido(s)</small></div><div className="metric-card"><span><AlertTriangle/>Exigem atenção</span><strong>{m.attention}</strong><small>Pagamento, teste ou bloqueio</small></div></div>
 <div className="dashboard-main-grid"><section className="panel"><div className="panel-head"><div><h2>Fila de atenção</h2><p className="panel-subtitle">Clientes que merecem uma ação do Master</p></div><Link to="/admin/lojas">Ver todas <ArrowRight size={14}/></Link></div>{attention.length===0?<div className="admin-clear"><CheckCircle2/><div><strong>Nenhuma pendência crítica</strong><small>A base está saudável neste momento.</small></div></div>:attention.map(s=><div className="activity-row" key={s.id}><span className="activity-icon warning"><AlertTriangle size={15}/></span><div><strong>{s.name}</strong><small>{s.ownerEmail||s.slug} · {s.subscriptionStatus==='past_due'?'Pagamento pendente':!s.active?'Acesso bloqueado':s.subscriptionStatus==='trial'?'Teste vencido':'Revisar assinatura'}</small></div><Link className="secondary-btn compact" to={`/admin/suporte/${s.id}`}><Headphones size={14}/>Abrir</Link></div>)}</section>
 <section className="panel"><div className="panel-head"><div><h2>Saúde da base</h2><p className="panel-subtitle">Distribuição rápida dos clientes</p></div></div><div className="health-progress"><div><span>Assinaturas ativas</span><strong>{m.active}</strong><i><b style={{width:`${stores.length?Math.round((m.active/stores.length)*100):0}%`}}/></i></div><div><span>Onboarding concluído</span><strong>{m.onboarding}</strong><i><b style={{width:`${stores.length?Math.round((m.onboarding/stores.length)*100):0}%`}}/></i></div><div><span>Em teste válido</span><strong>{m.trial}</strong><i><b style={{width:`${stores.length?Math.round((m.trial/stores.length)*100):0}%`}}/></i></div></div></section></div>
 <section className="panel"><div className="panel-head"><div><h2>Entradas recentes</h2><p className="panel-subtitle">Últimas lojas criadas na plataforma</p></div><Link to="/admin/lojas">Todos os clientes</Link></div>{recent.length===0?<p className="muted">Nenhuma loja cadastrada ainda.</p>:<div className="recent-store-grid">{recent.map(s=><article key={s.id}><div className="recent-store-avatar">{s.logoUrl?<img src={s.logoUrl} alt=""/>:s.name.slice(0,1).toUpperCase()}</div><div><strong>{s.name}</strong><small>{s.ownerEmail||s.slug}</small><span className={`subscription-mini ${s.subscriptionStatus||'trial'}`}>{s.subscriptionStatus==='active'?'Ativa':s.subscriptionStatus==='trial'?'Teste':s.subscriptionStatus==='past_due'?'Pendente':s.subscriptionStatus==='suspended'?'Suspensa':'Cancelada'}</span></div><Link to={`/admin/suporte/${s.id}`} title="Abrir suporte"><ArrowRight/></Link></article>)}</div>}</section></>;
}
